version: '3'
services:
  #  web:
  #    image: nginx:latest
  #    ports:
  #      - 80:80
  #    volumes:
  #      - ./web:/usr/share/nginx/html
  #    depends_on:
  #      - api
  #    links:
  #      - api:api
  #  web:
  #    build:
  #      context: .
  #      dockerfile: ./compose/springboot/Dockerfile
  #    volumes:
  #      - ./:/app/
  #    ports:
  #      - "8082:8082"
  #    depends_on:
  #      - mysql
  #    links:
  #      - mysql:mysql
  db:
    container_name: multimodule-mysql
    image: mysql:latest
    restart: always
    ports:
      - 3308:3306
    volumes:
      - mydata-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=zxcv1234
      - MYSQL_DATABASE=reservesite_db
      - MYSQL_USER=reservesite
      - MYSQL_PASSWORD=zxcv1234
      - TZ=Asia/Seoul
  subDb:
    container_name: multimodule-redis
    image: redis:latest
    restart: always
    hostname: reserve
    ports:
      - 6378:6379
volumes:
  mydata-volume:
